# importing required libraries
library(car) # advanced scatter plots 
library(corrplot) # plot correlations 
library(dplyr) # data aggregates 
library(gmodels) # cross tabulation
library(gplots) # plot means with CI 
library(psych) # descriptives
library(Hmisc) # for correlation test of multiple variables 
library(ggplot2) # for plots
library(ggthemes)
library(lubridate) # since dataset contains date field. Hence we might use it
library(tidyr)
library(DT)
library(scales)
library("Rserve") # For establishing connection between RStudio and Tableau

options(scipen = 99)

# importing the dataset
lyft1 <- read.csv("lyft1.csv", sep = ",", header = T)

# dataset contains extra indexing column named X so remove it
lyft1 = subset(lyft1, select = -c(X))

# creating a collection of colors
colors = c("#665555", "#05a399", "#f5e840","#e075b0")

# now extracting day, month, year and day of week from the Driver.Onboard.Date. 
lyft1$day <- as.factor(day(lyft1$Driver.Onboard.Date))

# label = TRUE assigns a character corresponding to the number. For example 1 is assigned January.
lyft1$month <- as.factor(month(lyft1$Driver.Onboard.Date, label = TRUE))
lyft1$year <- as.factor(year(lyft1$Driver.Onboard.Date))
lyft1$dayofweek <- as.factor(wday(lyft1$Driver.Onboard.Date, label = TRUE))

dev.off()

# Analyzing the onboarding months of various drivers
new_data = lyft1 %>% group_by(month) %>%summarise(frequency = n())
ggplot(new_data , aes(month,frequency))+geom_bar(stat = "identity",fill = "steelblue")+ggtitle("month")+scale_y_continuous(labels = comma)
#from the plot it is clear that maximum onboarding happened in the month of April.

new_data1 = lyft1 %>% group_by(month) %>%summarise(median(Total.Revenue.))
# From the output it is clear that drivers who joined early have brought in mor Total revenue.

# Calculating the total ride distance in miles of the drivers
lyft1$total <- lyft1$Average.Ride.Distance.in.Miles * lyft1$Number.of.Rides 

ggplot(lyft1,aes(dayofweek,total))+geom_bar(stat = "identity", fill = "red")
ggplot(lyft1,aes(dayofweek,Number.of.Rides))+geom_bar(stat = "identity", fill = "green")
ggplot(lyft1,aes(dayofweek,Total.Revenue.))+geom_bar(stat = "identity", fill = "steelblue")
# from the above three plots , it is clear that drivers travel more miles during midweek(i.e Tuesday, Wednesday, Thursday)
# they complete more number of rides during the same time frame and also the revenue generated by them high during midweek.

# now the dataset consists of number of rides in morning, day, night, late night. So lets see how these variables are influencing the Revenue generated by the drivers.
# for this we going to plot a correlation matrix.

scatterplotMatrix(~Total.Revenue.+Total.Late.Night+Total.Morning+Total.Day+Total.Night, data=lyft1, main="Scatter plot matrix for time of the rides and Revenue")

# observe the first row. From the plot, it is clear that Total.Night rides is highly correlated with the Total.Revenue.
# evident from the line with high positive slope. This means that drivers that complete more Night rides tend to generate more reveneue.

ggplot(lyft1,aes(dayofweek,Total.Night))+geom_bar(stat = "identity", fill = "steelblue")
# Again the maximum number of night rides by the drivers were done in midweek( i.e. tuesday, wwednesday, thursday)

# now lets analyze the relation between the prime rides and the revenue generated by them. But we are given only percentage of prime rides and total rides
# so to get total number of prime rides we write following line of code.

lyft1$no_of_prime_rides <- floor(lyft1$Percentage.of.Prime.Rides./100 * lyft1$Number.of.Rides) 

cor(lyft1$Total.Revenue., lyft1$no_of_prime_rides) 
# Bingo!!! highly positively correlated. This means more prime rides the drivers complete more revenue they bring in.

ggplot(lyft1 , aes(month,no_of_prime_rides))+geom_bar(stat = "identity" , fill = "yellow")
# And from the plot it is clear that the drivers who brought in more revenue completed the prime rides majorly in the month of April.

ggplot(lyft1 , aes(day, no_of_prime_rides))+geom_bar(stat = "identity" , fill = "green")

# now lets build a regression model to compute customer life time value.
# customer life time value is nothig but the revenue generated by the lyft drivers.

lyft1$normal_rides <- lyft1$Number.of.Rides - lyft1$no_of_prime_rides

cor(lyft1$Total.Revenue.,lyft1$normal_rides)
# more positively correlated than prime rides.

# Now lets build a regression model that predicts life time value of a driver.
# Taking all the relevant independent variables and running regression.

model <- lm(Total.Revenue. ~ no_of_prime_rides+normal_rides+Total.Late.Night+Total.Morning+Total.Day,Total.Night, data= lyft1)
summary(model)
#summary shows that all the variables are highly significant. All of them are significant at 95% confidence intervals.
#leaving Total.Late.Night all are also significant at 99% confidence interval.

# now lets check multicolinearity amongst the so called independent variables.
car::vif(model) # normal rides vif score is 10.34 means it should be removed.

# building a new model without normal_rides

new_model <- lm(Total.Revenue. ~ no_of_prime_rides+Total.Late.Night+Total.Morning+Total.Day+Total.Night, data = lyft1)
summary(new_model)
# all the variables are now highly significant at both 95% and 99% confidence intervals.
# but again vif score for prime_rides is >5 indicating multicollinearity. 
# hence best would be to keep only the below mentioned independent variables.

new <- lm(Total.Revenue. ~ Total.Late.Night+Total.Morning+Total.Day+Total.Night, data = lyft1)
summary(new)

car::vif(new) # all variables vif score is <5.


# Interpreting model ouput.
# If a driver does one late night ride he earns $14.86 keeping all other variables as constant.
# If a driver does one morning ride he earns $13.96 keeping all other variables as constant.
# If a driver does one day ride he earns $13.81 more keeping all other variables as constant.
# If a driver does one night ride he earns $12.79 more keeping all other variables as constant.

# Predciting Lifetime value of a driver i.e what revenue it brings to the company
# suppose in a month driver completes 10 Lates night rides, 15 morning rides, 25 Day rides and 12 Night rides
# then the revenue it brings to Lyft will be
test <- data.frame(Total.Late.Night = 10 , Total.Morning = 15, Total.Day = 25, Total.Night = 12)
predict(new, test )
# the driver earns $930.08 in one month. 

# Based on the company policies, Lyft might be charging a cut for each ride the driver completes and accordingly generates revenue.




